server:
  servlet:
    context-path: /api
  port: 9999
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 101MB
      file-size-threshold: 2KB
  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    database: MYSQL
    show-sql: false
    format_sql: true
    generate-ddl: false
    open-in-view: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.26.53.199:3306/dpm_business?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      connectionTimeout: 30000
      minimumIdle: 1
      maximumPoolSize: 5
      idleTimeout: 600000
      maxLifetime: 1800000
      autoCommit: true
      leakDetectionThreshold: 60000

logging:
  config: config/log4j2.yml
  # don't merge this config section. UAT only
  level:
    org:
      hibernate:
        SQL: DEBUG