server:
  servlet:
    context-path: /api
  port: 9999
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 101MB
      file-size-threshold: 2KB
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
    show-sql: false
    generate-ddl: false
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/sakila?createDatabaseIfNotExist=true
    username: root
    password: 123456
    hikari:
      connectionTimeout: 30000
      minimumIdle: 1
      maximumPoolSize: 5
      idleTimeout: 600000
      maxLifetime: 1800000
      autoCommit: true
      leakDetectionThreshold: 60000

logging:
  # don't merge this config section. UAT only
  level:
    org:
      hibernate:
        SQL: DEBUG
jwt:
  token:
    secretKey: mySecretKey