server:
  servlet:
    context-path: /api
  port: 9999
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 101MB
      file-size-threshold: 2KB
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: false
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 764783483803-27imov9a5i2qos9l51kv6mlgsdk8l4bd.apps.googleusercontent.com
            client-secret: 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
  datasource:
    url: jdbc:mysql://localhost:3306/sakila?createDatabaseIfNotExist=true
    username: root
    password: 123456
    hikari:
      connectionTimeout: 30000
      minimumIdle: 1
      maximumPoolSize: 5
      idleTimeout: 600000
      maxLifetime: 1800000
      autoCommit: true
      leakDetectionThreshold: 60000

logging:
  # don't merge this config section. UAT only
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        security: TRACE
jwt:
  token:
    secretKey: d813f4d4db12a3a31af54500ce1c1fa2f44b54c6d06dbb3ebc2277d0cb58f926


